### PR TITLE
Adapt icon path removal from core

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed prepares the plugin for the icon path removal from core in the upcoming LTS line. This change affects plugins not using the icon API or relying on paths. Plugins using the API properly in the first place are unaffected by this change.
In case of your plugin, I've removed the header icons, because that is what modern Jenkins does now look like.

Could you trigger a release after merging this PR please, giving people a chance to update the plugin before updating to the next LTS version @drekbour 
Thanks in advance!

### CODE REVIEW

**Comment by NotMyFault** [comment]
Any chance you could take care of this PR and cut a release? The next LTS baseline selection is currently ongoing @drekbour

**Comment by drekbour** [comment]
I'll try to merge tonight
-------- Original message --------From: Alexander Brandes ***@***.***> Date: 30/04/2022  12:14  (GMT+00:00) To: jenkinsci/ez-templates-plugin ***@***.***> Cc: drekbour ***@***.***>, Mention ***@***.***> Subject: Re: [jenkinsci/ez-templates-plugin] Adapt icon path removal from core (PR #9) 
Any chance you could take care of this PR and cut a release? The next LTS baseline selection is currently ongoing @drekbour

**Comment by NotMyFault** [comment]
Thanks for merging the PR, once released people are set to update.

**Comment by drekbour** [comment]
ez-templates-1.3.5 released. Note the build baselines are ancient as I've not really had cause to revisit this code in a long time.

**Pull request merged**
