### PR TITLE
Build Step which do not sync with Template Job

### PR DESCRIPTION
**Pull request by arpitgold**

### CODE REVIEW

**Comment by emoshaya-cognito** [comment]
So does this mean we can pick and choose which build step we want sync'd up with the template and which build steps we do?

**Comment by drekbour** [comment]
See https://github.com/JoelJ/ez-templates/pull/54 which is the same PR in the original repository. Very short summary:
1. You can achieve the same (albeit in a very ugly way) through the use of Conditional Build Step and Conditional Publisher plugins
2. EZ2 will support XPath templating which will cover any advanced case you can dream up.
3. This PR adds a huge amount of complexity for one use case (build steps) that will likely make it impossible for users to migrate from 1.x to 2.x

I can't really accept this PR although it has given me some good ideas about "placeholder build steps" to add the to the EZ2 requirements.

**Comment by arpit-nagar** [comment]
Hi @drekbour, 
I found this plugin very useful and solve many pains for maintain duplicate jobs.
We are still using placeholder approach in our environment. I want to sync with hosted plugin.
Do you have any rough timeline for EZ2.

**Comment by arpit-nagar** [comment]
@emoshaya-cognito 
Yes with this PR we can add steps for child job which will be only for that child job.
May be it can be complex in terms of maintaining/creating EZ plugin.
You can treat this PR as advanced syncing in EZ template. 
If you want to try it you can use attached hpi, which I am using

**Comment by arpit-nagar** [comment]
Hi @drekbour,

As a alternate solution;
Like other advance options, can we add another option to **do not sync Conditional steps**?
It will not add that much complexity in maintaining jobs. It will add capability for customization to do not sync some build steps. Only limitation to this, it will be applicable for once for each job for all conditional steps.
If you think it can be a short term acceptable solution, I can send a MR.
Please let me know your thoughts.

**Pull request closed without merging**
